- src/pages/Apps/New/:provider/Provider.bitbucket.js
- src/utils/api/Bitbucket.js
Add button to load more bitbucket repositories when creating a new app.
Implementation is similar to `load more` button of deployments page.
The current page size is set to 100 repositories.
Each trigger of the button loads another 100 repositories.
Resolves: #2
> feat: Add pagination for bitbucket repositories

- jsconfig.json
- tsconfig.json
We do not need a jsconfig because we already have a tsconfig. This PR removes the jsconfig and improves the tsconfig to allow relative imports.
> Fix: tsconfig and remove jsconfig

- package-lock.json
- package.json
- src/pages/Apps/New/:provider/Provider.bitbucket.js
- src/pages/Apps/New/:provider/Provider.github.js
- src/utils/api/Bitbucket.js
- src/utils/api/Github.js
Add button to load more bitbucket repositories when creating a new app.
Implementation is similar to load more button of deployments page.
The current page size is set to 100 repositories.
Each trigger of the button loads another 100 repositories.
Relates to: #2, #14
Adapt cleaner version of github provider.
Fix bug changing accounts/teams with async / await pattern in setState.
Relates to: #2, #14
> feat: Add pagination for github repositories

- tailwind.config.js
Apparently typescript files are ignored by tailwind and the classes are not included in the bundle. This PR fixes this bug.
> Fix: typescript support for tailwind purge

- src/layouts/_components/UserMenu.js
Before the stormkit menu could only be closed by clicking on the menu button and it was annoying. 
Now it can be closed by clicking outside of it.
I have added an "onclick" event to the document and I am checking if the user click is in the menu or not.
> Now the menu can be closed by clicking out of it.

- CODE_OF_CONDUCT.md
To make sure the community adheres to Stormkits standard of collaboration. This is the version provided by contributor-covenant. A more comprehensive alternative is also provided by GitHub.
> Create Code of Conduct file

- src/pages/apps/[id]/deployments/actions.js
The backend will soon use the new endpoint to publish deployments. The current endpoint returns a 404 anyways, so there is no problem if we update it beforehand.
> Fix: Update publish backend endpoint

- .prettierrc
- src/layouts/CenterLayout.tsx
This creates the `.prettierrc` config file for Prettier.
As prettier doesn't ["support any kind of global configuration"](https://prettier.io/docs/en/configuration.html), prettier might behave in an unexpected way on a different computer. For example, for me it tried added arrow parenthesis although they are avoided in the rest of the project.
> Create prettierrc config file

- src/pages/apps/new/New.spec.js
- src/utils/helpers/popup.js
Fixes the `window.open` function. Previously we used a mock function for unit tests which broke the implementation on Chrome.
> Fix: open popup function

- src/components/Errors/Error404.tsx
- src/pages/app/invitation/Accept.tsx
- src/pages/app/invitation/actions.ts
- src/pages/routes.tsx
This PR adds a page which handles team invitations. It'll parse the token provided in the URL and make a request to the backend. If everything looks fine, it'll redirect the user to the application's team page. Otherwise it will display a 404 page with a custom error message.
> Feat: add invitation accept page

- src/pages/apps/[id]/environments/_components/EnvironmentFormModal.spec.js
- src/pages/apps/[id]/environments/_components/EnvironmentFormModal.tsx
- src/pages/apps/[id]/environments/actions.tsx
- testing/nocks/nock_environment.js
When the environment variables are wiped out and the form is submitted, the environment page shows blank. This commit fixes that issue. Also, it migrates the EnvironmentFormModal file to typescript.
Issue: https://github.com/stormkit-io/app-stormkit-io/issues/157
> Fix: environment page being blank

- src/components/Form/Form.tsx
- src/components/Form/KeyValue.tsx
- src/pages/apps/[id]/environments/_components/EnvironmentFormModal.tsx
- src/pages/apps/[id]/environments/helpers.ts
@eldemcan I have refactored the environment variables part and moved that logic to the form component. This way we can reuse this logic in outbound webhooks.
> refactor: move logic to key-value component

- src/pages/apps/_components/AppHeader.tsx
If the app has never been deployed show "Not yet deployed" instead of the unix start time.
Refers to #300
> fix: check if the app has ever been deployed

- src/pages/apps/_components/DeployModal.tsx
Fixed an issue when the selected environment is not defined, also if the environment is not set the "Deploy now" button is now grayed out.
Refers to #208 and #302
> fix: check if the environment is undefined

- src/components/CopyBox/CopyBox.tsx
The trigger deploy link wasn't updating because it was set using the defaultValue property.
```defaultValue``` only specifies the value when the input is initially created
[https://github.com/facebook/react/issues/4101#issuecomment-111307019](https://github.com/facebook/react/issues/4101#issuecomment-111307019)
Fixes #226
> fix: update link of trigger deploys on env change

- src/pages/apps/[id]/settings/_components/FormTriggerDeploys.tsx
When the environment is changed, use the environment id instead of the environment name in the Trigger Deploy form.
> fix: use environment id for trigger deploy

- src/pages/apps/[id]/environments/actions.tsx
There were two problems:
1. Error resulting from duplicate environment names were not treated
2. Creating an environment, deleting it and recreating caused an error
This PR addresses the first problem. The second problem was fixed in backend, which resolves #361
> fix: handle duplicate env name

- src/components/Async/Async.tsx
- src/pages/apps/Apps.tsx
- src/pages/apps/new/bitbucket/NewBitbucketApp.tsx
- src/pages/apps/new/github/NewGithubApp.spec.tsx
- src/pages/apps/new/github/NewGithubApp.tsx
- src/pages/apps/new/gitlab/NewGitlabApp.tsx
- src/pages/auth/Auth.tsx
- src/pages/routes.tsx
Instead of including the layouts from the Route file, specify it as a lazy import when defining a route. This change allows us to wrap the file with the layout with a logic. It also beneficial for the tests because the layout won't generate unneeded markup anymore.
> refactor: specify layouts directly from the routes file

- src/pages/apps/[id]/environments/[env-id]/domain/_components/DomainVerificationStatus.tsx
Stormkit generates txt hostname and value for validating domain names and ask user ot add these values to their dns provider.
For the txt host name we follow <hash>.<domain> format. For example if user wants to validate vsk.me stormkit will ask to add txt record with hostname <hash>.vsk.me
This is a wrong directive because just adding hash as hostname would be enough. Providers concatanate domain name automatically.
As it can be seen from image adding 1234 as hostname and cloudflare already added `.gigs4peeps.com` if we add 1234.gigs4.peeps has txt name cloudflare will omit that.  Problem occurs with other domain providers such as namecheap unlike cloudflare and godady they don't omit **1234.gigs4.peeps** which causes conflic with root level txt name. By suggesting user to just use hash …
> chore: improve domain validation setup

- src/components/OutsideClick/OutsideClick.tsx
- src/layouts/_components/OutsideRefAlerter.tsx
- src/layouts/_components/UserButtons.tsx
Allow user and "what's news" modules to close when clicking outside of the buttons instead of expecting user to click on same button.
> feat: close modals when clicking outside

- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/index.ts
- src/pages/apps/[id]/environments/[env-id]/snippets/SnippetModal.spec.tsx
- src/pages/apps/[id]/environments/[env-id]/snippets/SnippetModal.tsx
- src/pages/apps/[id]/environments/[env-id]/snippets/Snippets.spec.tsx
- src/pages/apps/[id]/environments/[env-id]/snippets/Snippets.tsx
> chore: use dropdown for snipped host selection

- src/layouts/AppLayout/_components/DeployModal.spec.tsx
- src/layouts/AppLayout/_components/DeployModal.tsx
- src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigBuild.tsx
- src/pages/apps/[id]/environments/[env-id]/config/actions.spec.ts
- src/pages/apps/[id]/environments/[env-id]/config/actions.ts
- src/pages/apps/[id]/environments/helpers.ts
- src/pages/apps/actions.ts
- src/types/environment.d.ts
- testing/nocks/nock_deployments.ts
- testing/nocks/nock_environment.ts
We are introducing a new serverCmd variable, so renaming cmd to buildCmd will make things clearer.
> chore: rename property
