stormkit-io/app-stormkit-io

README.md
Updates the README to cover the environment variables.
=> Update README file to cover environment variables

package-lock.json, package.json, src/assets/styles/transitions.css, src/index.js, src/pages/Apps/New/:provider/Provider.bitbucket.js, src/pages/Apps/New/:provider/_components/RepoList.js
Add a spinner to the `load more` button in the bitbucket repository list
Resolves: #14
Fade in additionally loaded repositories.
This enhances the user experience while paginating through the repos.
Relates to: #14
=> Enhance user experience in bitbucket repository list

src/utils/api/Api.js
I found out that the last commit on master breaks the page after the login, so I've fixed the piece of code involved. Actually this is blocker if you create new branches from the master or make a pull
=> Fix: error page after login

src/pages/Apps/New/:provider/Provider.github.js, src/pages/Apps/New/:provider/Provider.spec.js
- Change connect more repositories to a text
- Add tests for github pagination
Here's a gif on how the pagination works:
=> Fix: Github pagination

src/assets/styles/tailwind.css, src/components/DotDotDot/DotDotDot.js, src/layouts/_components/AppMenu.js, src/pages/Apps/:id/Deployments/_components/Deployment.js, src/pages/Apps/:id/Environments/:envId/RemoteConfig/RemoteConfig.js, src/pages/Apps/:id/Environments/:envId/Snippets/Snippets.js, src/pages/Apps/:id/Environments/_components/Environment.js
- Refactor: use tooltip for the 404 warning message
- Feature: allow disabling dotx3 items
- Feature: link the logo in app menu to home page
- Refactor: change tooltip background to black
- Refactor: remove the explanation box and use the tooltip
=> Refactor: improve UX and design

src/components/InfoBox/InfoBox.tsx, src/pages/user/account/_components/SubscriptionDetails.tsx
@svedova I would test this component migration on my env, can you tell me where this component is displayed?
=> Typescript infobox migration

src/components/ConfirmModal/ConfirmModal.tsx, src/components/ConfirmModal/index.js, src/components/ConfirmModal/index.ts, src/pages/apps/[id]/environments/[env-id]/domain/Domain.js, src/pages/user/account/Account.tsx, src/pages/user/account/_components/PaymentDetails.tsx, src/pages/user/account/actions/fetch_cards.ts, src/pages/user/account/actions/handle_remove_payment_method.ts, src/pages/user/account/actions/handle_update_payments.ts, src/pages/user/account/actions/index.ts
- This PR adds the ability to remove a credit card from the saved cards. 
- Fixes a few bugs 
- Improves UX for loading states
=> Accounts page continued

src/components/ConfirmModal/ConfirmModal.tsx, src/pages/user/account/Account.tsx, src/pages/user/account/_components/PaymentDetails.tsx, src/pages/user/account/_components/SubscriptionDetails.tsx, src/pages/user/account/actions/fetch_subscriptions.ts, src/pages/user/account/actions/handle_update_subscription_plan.ts, src/pages/user/account/actions/index.ts
This PR allows upgrading and downgrading an application.
=> Handle subscriptions

src/pages/apps/[id]/environments/_components/EnvironmentFormModal.js, src/testing/nocks/nock_environment.js
The `auto publish` toggle in Environment settings modal does not show the default selected value correctly. This PR fixes the issue.
=> Fix: fix default toggle value

src/pages/apps/Apps.spec.js, src/pages/apps/Apps.tsx, src/pages/apps/actions.ts, src/testing/helpers.js, src/testing/nocks/nock_app.ts
Closes #4 
This PR adds pagination to the application list. The `Load More` button will be invisible until the api returns `hasNextPage: true`.
=> 4 implement pagination

src/utils/api/Api.js
=> Fix: redirect the user to auth page when an XHR request fails

src/layouts/DefaultLayout.tsx, src/layouts/MenuLayout.tsx, src/layouts/_components/UserMenu.tsx, src/pages/apps/[id]/environments/_components/EnvironmentFormModal.js, src/pages/apps/[id]/settings/_components/FormAppSettings.spec.js, src/pages/apps/[id]/settings/_components/FormAppSettings.tsx, src/pages/apps/new/[provider]/_components/Accounts.js
This PR fixes the regression caused by the recent `Form.Select` API change.
=> Fix: form select API change

src/components/DotDotDot/DotDotDot.tsx, src/pages/apps/Apps.tsx, src/pages/apps/[id]/deployments/Deployments.spec.js, src/pages/apps/[id]/deployments/Deployments.tsx, src/pages/apps/[id]/deployments/[deployment-id]/Deployment.spec.js, src/pages/apps/[id]/deployments/_components/Deployment.tsx, src/pages/apps/[id]/deployments/_components/ExitStatus.tsx, src/pages/apps/[id]/deployments/actions.ts, src/pages/apps/[id]/environments/[env-id]/remote-config/_components/Parameter.js, src/pages/apps/[id]/environments/[env-id]/snippets/_components/SnippetTable.js, src/pages/apps/[id]/team/Team.js, src/types/deployment.d.ts, testing/data/mock_deployments_response.js, testing/nocks/nock_deployments.js
This PR adds a button to stop a deployment.
It is related to https://github.com/stormkit-io/app-stormkit-io/issues/130.
=> Add stop deployment button

src/pages/apps/[id]/settings/_components/FormAppSettings.tsx, src/pages/apps/[id]/settings/actions.js
=> Feat: add support for nodejs 14

src/pages/apps/[id]/settings/_components/FormAppSettings.tsx
Removes NodeJS 10 from the dropdown in the application settings page.
=> Feat: remove nodejs10 from dropdown

config/webpack.config.js, package-lock.json, package.json
Es build is a new kid in the block making blazing fast builds.  https://esbuild.github.io/ 
We can use it in conjunction with webpack.  This will improve stormkits deployment time
=> Use esbuild to create bundle

.github/workflows/commitlint.yml
Introduces https://commitlint.js.org/#/ into our actions.
=> feat: introduce commit linter

src/pages/apps/_components/DeployModal.tsx
When environment is changed, refresh the deploy settings.
Fixes #221
=> fix: refresh deploy settings

src/components/Form/Input.tsx, src/components/Logo/Logo.tsx, src/pages/apps/_components/DeployModal.tsx, src/public/index.html
=> Onboarding

src/components/Form/KeyValue.tsx, src/pages/apps/[id]/environments/_components/EnvironmentFormModal.spec.js, src/pages/apps/[id]/environments/_components/EnvironmentFormModal.tsx, src/pages/apps/[id]/settings/_actions/outbound_webhook_actions.tsx, src/pages/apps/[id]/settings/_components/FormOutboundWebhookModal.spec.js, src/pages/apps/[id]/settings/_components/FormOutboundWebhookModal.tsx, src/pages/apps/[id]/settings/actions.tsx, src/pages/apps/[id]/settings/types.d.ts, src/utils/helpers/array.ts
=> feat: header component for outbound webhook

src/pages/apps/new/[provider]/Provider.bitbucket.js, src/pages/apps/new/[provider]/Provider.github.js, src/pages/apps/new/[provider]/Provider.gitlab.js, src/pages/apps/new/[provider]/Provider.js
I have added a basic implementation of a search bar that allows you to filter the list of repositories by their name.
Refers to #164 and #161 
Demo of the implementation:
=> feat: filter repos by name on app creation

src/pages/apps/[id]/environments/_components/EnvironmentFormModal.tsx, src/pages/apps/_components/DeployModal.tsx
=> chore: update wording for build commands

src/pages/apps/[id]/environments/_components/Environment.tsx, src/pages/apps/[id]/environments/_components/EnvironmentFormModal.tsx, src/pages/apps/[id]/settings/Settings.tsx, src/pages/apps/[id]/settings/_components/FormAppSettings.spec.js, src/pages/apps/[id]/settings/_components/FormAppSettings.tsx, src/pages/apps/[id]/settings/actions.tsx, testing/nocks/nock_update_settings.js
- deprecated app level auto deploy
- introduced env level auto deploy
=> feat: move auto deploy config to env config

src/pages/apps/new/[provider]/_components/Accounts.js
=> fix: avatar position

src/pages/apps/[id]/environments/_components/Environment.tsx
=> feat: delete environment from dropdown

src/pages/apps/[id]/settings/_components/FormTriggerDeploys.tsx
The key was set to the wrong component and react was complaining about it.
=> Unique key on parent component

src/pages/apps/[id]/environments/[env-id]/remote-config/RemoteConfig.js
=> fix: tooltip alignment

src/pages/apps/[id]/deployments/_components/CommitInfo.tsx, src/pages/apps/[id]/deployments/_components/Deployment.tsx
quick win for https://github.com/stormkit-io/app-stormkit-io/issues/397
=> chore: add sha information to deployment item

package-lock.json, package.json, src/pages/apps/[id]/deployments/_components/Deployment.tsx, src/pages/apps/[id]/deployments/_components/Manifest.tsx, src/pages/apps/[id]/deployments/actions.ts
=> Show manifest

src/pages/apps/[id]/environments/[env-id]/deployments/runtime-logs/RuntimeLogs.tsx
Log logs doesn't break to next line in log view, this pr adds break for it
=> chore: add word break for logs

src/pages/apps/[id]/environments/[env-id]/deployments/runtime-logs/RuntimeLogs.spec.tsx, src/pages/apps/[id]/environments/[env-id]/deployments/runtime-logs/RuntimeLogs.tsx, src/pages/apps/[id]/environments/[env-id]/deployments/runtime-logs/actions.ts, testing/nocks/nock_logs.ts
=> chore: minor ui improvements

src/layouts/AppLayout/AppLayout.spec.tsx, src/layouts/AppLayout/menu_items.ts, src/pages/apps/[id]/App.context.tsx, src/pages/apps/[id]/actions.ts, src/pages/apps/[id]/environments/[env-id]/datastore/Collections.spec.tsx, src/pages/apps/[id]/environments/[env-id]/datastore/Collections.tsx, src/pages/apps/[id]/environments/[env-id]/datastore/Records.spec.tsx, src/pages/apps/[id]/environments/[env-id]/datastore/Records.tsx, src/pages/apps/[id]/environments/[env-id]/datastore/actions.ts, src/pages/apps/[id]/environments/[env-id]/datastore/index.ts, src/pages/apps/[id]/environments/[env-id]/feature-flags/FeatureFlags.tsx, src/pages/apps/[id]/environments/[env-id]/feature-flags/actions.ts, src/pages/apps/[id]/environments/[env-id]/routes.ts, src/types/app.d.ts, src/types/data-store.d.ts, testing/data/mock_collection_records.ts, testing/data/mock_collections.ts, testing/nocks/nock_datastore.ts
- attach production feature flags to app
=> feat: display data store collections and records

src/layouts/AppLayout/menu_items.ts, src/pages/apps/[id]/environments/[env-id]/function-triggers/FunctionTriggers.spec.tsx, src/pages/apps/[id]/environments/[env-id]/function-triggers/FunctionTriggers.tsx, src/pages/apps/[id]/environments/[env-id]/function-triggers/_components/FunctionTriggerModal.spec.tsx, src/pages/apps/[id]/environments/[env-id]/function-triggers/_components/FunctionTriggerModal.tsx, src/pages/apps/[id]/environments/[env-id]/function-triggers/actions.ts, src/pages/apps/[id]/environments/[env-id]/function-triggers/index.ts, src/pages/apps/[id]/environments/[env-id]/routes.ts, src/types/function-triggers.d.ts, src/utils/api/Api.ts, testing/data/mock_function_triggers.ts, testing/nocks/nock_function_triggers.ts
Changes are behind feature flag.
=> feat: add UI for trigger functions feature

src/layouts/_components/UserButtons.tsx
this pr adds label for admins to see if we switch to canary environment, admin can turn on off switching between prod and canary
=> feat: all label for environment

src/pages/apps/Apps.tsx, src/pages/apps/_components/EmptyList.spec.tsx, src/pages/apps/_components/EmptyList.tsx, src/utils/helpers/string.ts
=> feat: add import from url to the empty list

src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigGeneral.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigServerless.tsx, src/pages/apps/[id]/environments/[env-id]/config/actions.spec.ts, src/pages/apps/[id]/environments/[env-id]/config/actions.ts, src/types/environment.d.ts, src/utils/api/Api.ts
- fix: several minor bugs related to the environment config
- chore: add specs for buildFormValues method
=> feat: introduce serverless path prefix

src/components/AppName/AppName.spec.tsx, src/components/AppName/AppName.tsx, src/components/MenuLink/MenuLink.tsx, src/layouts/AppLayout/AppLayout.spec.tsx, src/layouts/AppLayout/AppLayout.tsx, src/layouts/AppLayout/AppMenu.tsx, src/pages/apps/Apps.tsx
=> feat: add a link to turn back to my apps page

src/components/Card/Card.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/RedirectsEditor.spec.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/RedirectsEditor.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/RedirectsPlaygroundModal.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigGeneral.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigRedirects.spec.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigRedirects.tsx, src/pages/apps/[id]/environments/[env-id]/config/actions.spec.ts, src/pages/apps/[id]/environments/[env-id]/config/actions.ts, src/pages/mui-theme.tsx, src/shared/deployments/ManifestModal/TabRedirects.tsx, src/types/environment.d.ts, testing/nocks/nock_environment.ts
- Users will now be able to define redirects directly from the UI. 
- These redirects will be merged with deployment redirects (if any) and will take precedence.
=> Introduce environment level redirects

src/components/FormV2/KeyValue.tsx, src/components/FormV2/KeyValueRow.tsx, src/components/FormV2/KeyValueTextFieldModal.tsx, src/pages/apps/[id]/environments/[env-id]/config/EnvironmentConfig.spec.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigEnvVars.spec.tsx, src/pages/apps/[id]/environments/[env-id]/config/_components/TabConfigEnvVars.tsx, src/pages/mui-theme.tsx
- Implement a button to toggle environment variable visibility
- Re-organize code by separating logic into smaller components
- Write a spec for TabConfigEnvVars
=> feat: hide environment variables

src/components/CardRow/CardRow.tsx, src/layouts/AppLayout/AppLayout.spec.tsx, src/layouts/AppLayout/AppMenu.tsx, src/layouts/TeamLayout/TeamLayout.tsx, src/layouts/TeamLayout/TeamNav.tsx, src/layouts/TopMenu/Teams/TeamMenu.tsx, src/layouts/TopMenu/Teams/TeamToggle.tsx, src/layouts/TopMenu/Teams/actions.ts, src/layouts/TopMenu/UserMenu.spec.tsx, src/layouts/TopMenu/UserMenu.tsx, src/pages/auth/actions.ts, src/pages/team/InviteMemberModal.tsx, src/pages/team/Settings.spec.tsx, src/pages/team/TeamDelete.spec.tsx, src/pages/team/TeamDelete.tsx, src/pages/team/TeamMembers.spec.tsx, src/pages/team/TeamMembers.tsx, src/pages/team/TeamSettings.spec.tsx, src/pages/team/TeamSettings.tsx, vite.config.ts
- When the home page is visited, display the last selected team. 
- Hide action buttons for developer roles in Team Settings page.
- Allow customizing page title through `STORMKIT_PAGE_TITLE` environment variable
=> Default team

src/components/Card/Card.tsx, src/components/CardHeader/CardHeader.tsx, src/components/UserAvatar/UserAvatar.tsx, src/components/UserAvatar/index.ts, src/layouts/TopMenu/UserButtons.tsx, src/pages/apps/Apps.spec.tsx, src/pages/apps/Apps.tsx, src/pages/apps/[id]/environments/_components/EnvironmentStatus.spec.tsx, src/pages/apps/_components/EmptyList.spec.tsx, src/pages/apps/_components/EmptyList.tsx, src/pages/apps/_components/__snapshots__/WelcomeModal.spec.tsx.snap, src/pages/auth/Auth.spec.tsx, src/pages/auth/Auth.tsx, src/pages/auth/BasicAuthLogin.spec.tsx, src/pages/auth/BasicAuthLogin.tsx, src/pages/auth/BasicAuthRegister.spec.tsx, src/pages/auth/BasicAuthRegister.tsx, src/pages/auth/ProviderAuth.tsx, src/pages/auth/actions.ts, src/pages/user/account/_components/UserProfile.tsx, src/testing/helpers.tsx, src/testing/nocks/nock_user.ts, src/utils/api/Api.ts
- Improve the onboarding experience by introducing an admin account creation and login screen for self-hosted users who did not configure a provider
- Improve the empty list design
=> Admin login

src/components/ButtonDropdown/ButtonDropdown.tsx, src/pages/admin/Subscription.tsx
This PR fixes the bug on the mobile devices which prevented users creating new apps. The problem was a bug with MUI which happens when ClickAwayListener is combined with Tooltip. The solution was to revert the order.
=> Fix mobile interaction
